<meta name="google-site-verification" content="${google-site-verification}">
theme: jekyll-theme-merlot
google-site-verification: wLlaRXwHlSFyxFQiiQ_-rt8xTNUR56NaJkgdTBhBIac
kramdown:
  input: Kramdown
